### ISSUE TITLE
_oasis_remove_.ml and *.install are created in wrong directory

### ISSUE THREAD

**Issue by hcarty** [ocaml/oasis2opam#26]
These files were in `opam/files/` previously and now they are created in the project root with oasis2opam 0.7.

**Comment by Chris00** [comment]
This is on purpose.  The content of `opam/files/` is copied to the root of the project by OPAM anyway and [it was requested](https://github.com/ocaml/oasis2opam/issues/24) that these files be in the tarball and not in opam metadata.  This is why prefer *not* to put them in `opam/` because one should be able to copy it to `opam-respository` and adapt it to publish the package.

**Comment by Chris00** [comment]
Note that, when then next version of oasis is released, `_oasis_remove_.ml` will become obsolete (and `oasis2opam` will let you know that you should remove it).

**Comment by hcarty** [comment]
Ah, I see.  Thank you for the explanation!
